### ISSUE TITLE
Issue with latest rethinkdb version

### ISSUE THREAD

**Issue by darrencauthon** [kilt-cms/kilt-cms#25]
Ran bundle install on a new Rails project, and got rethinkdb version 1.12.0.0.  Also got the following error:

```
/Users/darrencauthon/.rvm/gems/ruby-2.1.0/gems/rethinkdb-1.12.0.0/lib/func.rb:104:in `define_method': wrong argument type Symbol (expected Proc/Method) (TypeError)
    from /Users/darrencauthon/.rvm/gems/ruby-2.1.0/gems/rethinkdb-1.12.0.0/lib/func.rb:104:in `block (2 levels) in <class:RQL>'
    from /Users/darrencauthon/.rvm/gems/ruby-2.1.0/gems/rethinkdb-1.12.0.0/lib/func.rb:103:in `each'
    from /Users/darrencauthon/.rvm/gems/ruby-2.1.0/gems/rethinkdb-1.12.0.0/lib/func.rb:103:in `block in <class:RQL>'
    from /Users/darrencauthon/.rvm/gems/ruby-2.1.0/gems/rethinkdb-1.12.0.0/lib/func.rb:59:in `each'
    from /Users/darrencauthon/.rvm/gems/ruby-2.1.0/gems/rethinkdb-1.12.0.0/lib/func.rb:59:in `<class:RQL>'
    from /Users/darrencauthon/.rvm/gems/ruby-2.1.0/gems/rethinkdb-1.12.0.0/lib/func.rb:2:in `<module:RethinkDB>'
    from /Users/darrencauthon/.rvm/gems/ruby-2.1.0/gems/rethinkdb-1.12.0.0/lib/func.rb:1:in `<top (required)>'
    from /Users/darrencauthon/.rvm/gems/ruby-2.1.0/gems/rethinkdb-1.12.0.0/lib/rethinkdb.rb:11:in `load'
    from /Users/darrencauthon/.rvm/gems/ruby-2.1.0/gems/rethinkdb-1.12.0.0/lib/rethinkdb.rb:11:in `<top (required)>'
    from /Users/darrencauthon/Desktop/kilt/lib/kilt/engine.rb:2:in `require'
    from /Users/darrencauthon/Desktop/kilt/lib/kilt/engine.rb:2:in `<top (required)>'
    from /Users/darrencauthon/Desktop/kilt/lib/kilt/base.rb:1:in `require'
```

The error went away when I forced version 1.11.0.2.  

This may not be an issue with Kilt, but just wanted to share it here.

**Comment by darrencauthon** [comment]
This is resolved in #27, which stops using the REPL interface.
